"""Generate PostgreSQL DDL from an application definition."""
from psycopg import sql

from .definition import Default, Definition, Entity, FieldDef
from .names import quote, schema_for, check_ident


def _default_sql(d: Default) -> sql.Composable:
    if d.kind == "number":
        return sql.SQL(d.value)  # validated numeric literal from the analyser
    if d.kind == "string":
        return sql.Literal(d.value or "")
    if d.kind == "boolean":
        return sql.SQL(d.value or "false")
    if d.kind == "now":
        return sql.SQL("current_timestamp")
    return sql.SQL("current_date")


def _column(f: FieldDef) -> sql.Composable:
    parts = [sql.Identifier(check_ident(f.name)), sql.SQL(f.type)]  # type strings come from typemap only
    if f.identity:
        parts.append(sql.SQL("generated by default as identity"))
    if f.required:
        parts.append(sql.SQL("not null"))
    if f.default and not f.identity:
        parts += [sql.SQL("default"), _default_sql(f.default)]
    if f.max_length is not None:  # citext has no length, so the size from Access is a check
        parts.append(sql.SQL("check (char_length({}) <= {})").format(sql.Identifier(f.name), sql.Literal(int(f.max_length))))
    return sql.SQL(" ").join(parts)


def _ids(cols: list[str]) -> sql.Composable:
    return sql.SQL(", ").join(sql.Identifier(check_ident(c)) for c in cols)


def create_table(slug: str, e: Entity) -> list[sql.Composable]:
    schema = sql.Identifier(schema_for(slug))
    table = sql.Identifier(check_ident(e.name))
    cols = [_column(f) for f in e.fields]
    if e.primary_key:
        cols.append(sql.SQL("primary key ({})").format(_ids(e.primary_key)))
    stmts = [sql.SQL("create table {}.{} ({})").format(schema, table, sql.SQL(", ").join(cols))]
    for ix in e.indexes:
        stmts.append(sql.SQL("create {} index {} on {}.{} ({})").format(
            sql.SQL("unique" if ix.unique else ""), sql.Identifier(check_ident(ix.name)), schema, table, _ids(ix.columns)))
    return stmts


def add_foreign_key(slug: str, e: Entity, fk) -> sql.Composable:
    schema = sql.Identifier(schema_for(slug))
    return sql.SQL("alter table {s}.{t} add constraint {n} foreign key ({c}) references {s}.{r} ({rc})").format(
        s=schema, t=sql.Identifier(e.name), n=sql.Identifier(check_ident(fk.name)), c=_ids(fk.columns),
        r=sql.Identifier(check_ident(fk.ref_entity)), rc=_ids(fk.ref_columns))


def orphan_count(slug: str, e: Entity, fk) -> sql.Composable:
    schema = sql.Identifier(schema_for(slug))
    on = sql.SQL(" and ").join(
        sql.SQL("p.{} = c.{}").format(sql.Identifier(rc), sql.Identifier(c)) for c, rc in zip(fk.columns, fk.ref_columns))
    any_null = sql.SQL(" or ").join(sql.SQL("c.{} is null").format(sql.Identifier(c)) for c in fk.columns)
    return sql.SQL("select count(*) from {s}.{t} c where not ({n}) and not exists (select 1 from {s}.{r} p where {on})").format(
        s=schema, t=sql.Identifier(e.name), n=any_null, r=sql.Identifier(fk.ref_entity), on=on)


AUDIT_TRIGGER = "a2w_audit"


def audit_trigger(slug: str, e: Entity) -> sql.Composable:
    return sql.SQL("create trigger {} after insert or update or delete on {}.{} "
                   "for each row execute function a2w_control.record_change()").format(
        sql.Identifier(AUDIT_TRIGGER), sql.Identifier(schema_for(slug)), sql.Identifier(e.name))


def role_for(slug: str) -> str:
    return schema_for(slug)  # one role for each application, named like its schema


def grant_role(slug: str, d: Definition) -> list[sql.Composable]:
    schema, role = sql.Identifier(schema_for(slug)), sql.Identifier(role_for(slug))
    stmts: list[sql.Composable] = [sql.SQL("grant usage on schema {} to {}").format(schema, role)]
    for e in d.entities:
        stmts.append(sql.SQL("grant select, insert, update, delete on {}.{} to {}").format(schema, sql.Identifier(e.name), role))
    return stmts
